 version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    container_name: komek-db
    volumes:
      - komek-db:/var/lib/postgresql/data
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=secret
    networks:
      - komek

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "8888:8888"
#    volumes:
#      - ./:/app/
#    container_name: komek-app
#    networks:
#      - komek
#    depends_on:
#      - db
#    command: air main.go

  cache:
    image: redis:7.0-alpine
    restart: unless-stopped
    container_name: komek-cache
    ports:
      - '6380:6379'
    networks:
      - komek
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes:
      - cache:/data

volumes:
  cache:
  komek-db:

networks:
  komek:
    driver: bridge
    name: komek