version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    volumes:
      - komek-db:/var/lib/postgresql/data
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=secret
    networks:
      - komek

volumes:
  komek-db:

networks:
  komek:
    driver: bridge
    name: komek