// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Organisation struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Bin       string       `json:"bin"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Name          sql.NullString `json:"name"`
	Login         string         `json:"login"`
	Email         sql.NullString `json:"email"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	PasswordHash  string         `json:"password_hash"`
	Phone         sql.NullString `json:"phone"`
	Roles         string         `json:"roles"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
