// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package word_db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Login     string    `json:"login"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Word struct {
	FkUserID    uuid.NullUUID `json:"fk_user_id"`
	Value       string        `json:"value"`
	Language    string        `json:"language"`
	Translation string        `json:"translation"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}
