// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users_query.sql

package word_db

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, name, login, email, phone, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Login,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, login, email, phone, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Login,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUser = `-- name: RemoveUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) RemoveUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, removeUser, id)
	err := row.Scan(&id)
	return id, err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO users(
    id, name, login, email, phone, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)
)
RETURNING id
`

type SaveUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Login string    `json:"login"`
	Email string    `json:"email"`
	Phone string    `json:"phone"`
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, saveUser,
		arg.ID,
		arg.Name,
		arg.Login,
		arg.Email,
		arg.Phone,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET id = $1,
    name = $2,
    login = $3,
    email = $4,
    phone = $5,
    updated_at = CURRENT_TIMESTAMP(6)
WHERE id = $1
RETURNING id
`

type UpdateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Login string    `json:"login"`
	Email string    `json:"email"`
	Phone string    `json:"phone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Login,
		arg.Email,
		arg.Phone,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
