app:
  name: 'komek'
  version: '1.0.0'

http:
  port: '8887'
  timeout: '15s'

grpc:
  port: '8886'

logger:
  log_level: 'local'

postgres:
  user: "app"
  password: "secret"
#  host: "komek-db"
  host: "localhost"
#  port: "5432"
  port: "5433"
  name: "app"
  pool_max: 2
  ssl_mode: "disable"

redis:
#  addr: "komek-cache:6379"
  addr: "localhost:6381"
  user: ""
  password: "secret"
  enable_tls: false

locker:
  lock_timeout: '3m'

token:
  access_token_lifetime: '4h'
  refresh_token_lifetime: '24h'

oauth2:
  service_addr: 'http://localhost:8081'
  auth_url: 'http://localhost:9010/oauth2/auth'
  token_url: 'http://localhost:9010/oauth2/token'
  redirect_url: 'http://localhost:8888/callback'
  client_id: '321ffb75-c57b-4f11-866c-63fd1a561ddb'
  client_secret: 'mysecret'
  scopes:
    - offline
    - users.write
    - users.read
    - users.edit
    - users.delete

cookie:
  secret: 'secret'

banking_service:
  addr: ":8889"
  enable_tls: false