app:
  name: 'komek'
  version: '1.0.0'

http:
  port: '8888'
  timeout: '15s'

logger:
  log_level: 'local'

postgres:
  user: "app"
  password: "secret"
  host: "localhost"
  port: "5435"
  name: "app"
  pool_max: 2
  ssl_mode: "disable"

redis:
  addr: "localhost:6381"
  password: "secret"

locker:
  lock_timeout: '3m'

oauth2:
  service_addr: 'http://localhost:8081'
  auth_url: 'http://localhost:9010/oauth2/auth'
  token_url: 'http://localhost:9010/oauth2/token'
  redirect_url: 'http://localhost:8888/callback'
  client_id: '321ffb75-c57b-4f11-866c-63fd1a561ddb'
  client_secret: 'mysecret'
  scopes:
    - offline
    - users.write
    - users.read
    - users.edit
    - users.delete

cookie:
  secret: 'secret'