app:
  name: 'komek'
  version: '1.0.0'

http:
  port: '8888'

logger:
  log_level: 'local'

postgres:
  user: "app"
  password: "secret"
  host: "localhost"
  port: "5433"
  name: "app"
  pool_max: 2
  ssl_mode: "disable"
