app:
  name: 'komek'
  version: '1.0.0'

http:
  port: '8888'

logger:
  log_level: 'local'

postgres:
  user: "app"
  password: "secret"
  host: "db"
  port: "5432"
  name: "app"
  pool_max: 2
  ssl_mode: "disable"

redis:
  addr: "cache:6379"
  password: "secret"

locker:
  lock_timeout: '3m'