app:
  name: 'komek'
  version: '1.0.0'

http:
  port: '8888'
  timeout: '15s'

logger:
  log_level: 'local'

postgres:
  user: "app"
  password: "secret"
  host: "db"
  port: "5432"
  name: "app"
  pool_max: 2
  ssl_mode: "disable"

redis:
  addr: "cache:6379"
  password: "secret"

locker:
  lock_timeout: '3m'

oauth2:
  url:
    auth: "http://localhost:9010/oauth2/auth"
    token: "http://localhost:9010/oauth2/token"
    redirect: "http://localhost:8888/callback"
  config:
    client_id: "1ac9df27-ade0-4f03-b434-b17337b6411e"
    client_secret: "mysecret"
    scopes:
      - offline
      - users.write
      - users.read
      - users.edit
      - users.delete

oauth_service:
  addr: 'http://localhost:8081'
  client_id: '1ac9df27-ade0-4f03-b434-b17337b6411e'
  client_secret: 'mysecret'

cookie:
  secret: 'secret'